const ui={ru:{hero:"Ежедневное чтение Библии",plan:"План Победы 2026",full:"Открыть весь план",language:"Языки пользования",read:"✓ Я прочитал",readDone:"Прочитано ✅",notes:"Мои заметки",placeholder:"Что Бог сказал мне сегодня?",save:"Сохранить заметку",saved:"Заметка сохранена",noteInfo:"Ваши заметки сохраняются только на этом устройстве.",progress:"Мой прогресс",readCount:"Прочитано",missed:"Пропущено",total:"Всего",calendar:"Календарь прогресса",navToday:"Сегодня",navCalendar:"Календарь прогресса",navNotes:"Заметки",navProgress:"Прогресс",day:"День",of:"из",todayLabel:"Сегодня:",missing:"Этот день ещё нужно добавить в план.",winner:"Ты победитель!",winnerText:"Сегодня ты сделал важный духовный шаг.",amen:"Аминь"},uk:{hero:"Щоденне читання Біблії",plan:"План Перемоги 2026",full:"Відкрити весь план",language:"Мови користування",read:"✓ Я прочитав",readDone:"Прочитано ✅",notes:"Мої нотатки",placeholder:"Що Бог сказав мені сьогодні?",save:"Зберегти нотатку",saved:"Нотатку збережено",noteInfo:"Ваші нотатки зберігаються тільки на цьому пристрої.",progress:"Мій прогрес",readCount:"Прочитано",missed:"Пропущено",total:"Усього",calendar:"Календар прогресу",navToday:"Сьогодні",navCalendar:"Календар прогресу",navNotes:"Нотатки",navProgress:"Прогрес",day:"День",of:"з",todayLabel:"Сьогодні:",missing:"Цей день ще потрібно додати в план.",winner:"Ти переможець!",winnerText:"Сьогодні ти зробив важливий духовний крок.",amen:"Амінь"},en:{hero:"Daily Bible Reading",plan:"Victory Plan 2026",full:"Open full plan",language:"User languages",read:"✓ I read today",readDone:"Read ✅",notes:"My notes",placeholder:"What did God speak to me today?",save:"Save note",saved:"Note saved",noteInfo:"Your notes are saved only on this device.",progress:"My Progress",readCount:"Read",missed:"Missed",total:"Total",calendar:"Progress calendar",navToday:"Today",navCalendar:"Progress calendar",navNotes:"Notes",navProgress:"Progress",day:"Day",of:"of",todayLabel:"Today:",missing:"This day still needs to be added to the plan.",winner:"You are a winner!",winnerText:"Today you made an important spiritual step.",amen:"Amen"}};
let lang=localStorage.getItem("lang")||"ru";let now,key,dayOfYear;
function updateTodayData(){now=new Date();key=String(now.getMonth()+1).padStart(2,"0")+"-"+String(now.getDate()).padStart(2,"0");dayOfYear=Math.floor((now-new Date(now.getFullYear(),0,0))/86400000)}
function setLang(l){lang=l;localStorage.setItem("lang",l);refreshApp()}
function parseReadings(text){let parts=text.split(",").map(x=>x.trim()).filter(Boolean),out=[],current=null;for(const part of parts){let found=null,rest="";for(const b of bookOrder){if(part===b||part.startsWith(b+" ")){found=b;rest=part.slice(b.length).trim();break}}if(found){current=found;(rest.match(/\d+/g)||[]).forEach(n=>out.push({book:current,chapter:n}))}else if(current){(part.match(/\d+/g)||[]).forEach(n=>out.push({book:current,chapter:n}))}}return out}
function bibleUrl(book,chapter){const passage=encodeURIComponent(bookQueries[book]+" "+chapter);return "https://www.biblegateway.com/passage/?search="+passage+"&version="+versions[lang]}
function refreshApp(){updateTodayData();applyLang();renderReading();renderProgress();loadTodayNote()}
function applyLang(){const t=ui[lang];document.documentElement.lang=lang;heroTitle.innerText=t.hero;planTitle.innerText=t.plan;fullPlanBtn.innerText=t.full;languageTitle.innerText=t.language;notesTitle.innerText=t.notes;note.placeholder=t.placeholder;saveNoteBtn.innerText=t.save;noteInfo.innerText=t.noteInfo;progressTitle.innerText=t.progress;readText.innerText=t.readCount;missedText.innerText=t.missed;totalText.innerText=t.total;calendarBtn.innerText=t.calendar;navToday.innerText=t.navToday;navCalendar.innerText=t.navCalendar;navNotes.innerText=t.navNotes;winnerTitle.innerText=t.winner;winnerText.innerText=t.winnerText;winnerBtn.innerText=t.amen;document.querySelectorAll(".lang button").forEach(b=>b.classList.remove("active"));document.getElementById("btn-"+lang).classList.add("active");todayDate.innerText=t.todayLabel+" "+now.toLocaleDateString(lang==="en"?"en-US":lang==="uk"?"uk-UA":"ru-RU",{day:"numeric",month:"long",year:"numeric"});dayNumber.innerText=t.day+" "+dayOfYear+" "+t.of+" 365";if(localStorage.getItem("read-"+key)){readBtn.innerText=t.readDone;readBtn.classList.add("done")}else{readBtn.innerText=t.read;readBtn.classList.remove("done")}}
function renderReading(){const text=planText[key];if(!text){reading.innerHTML="<div class='chapter-btn'>"+ui[lang].missing+"</div>";return}reading.innerHTML=parseReadings(text).map(r=>{const title=(bookLabels[lang][r.book]||r.book)+" "+r.chapter;return `<a class="chapter-btn" target="_blank" href="${bibleUrl(r.book,r.chapter)}">${title}</a>`}).join("")}
readBtn.onclick=function(){updateTodayData();localStorage.setItem("read-"+key,"yes");refreshApp();winnerModal.style.display="flex"};
function closeWinner(){winnerModal.style.display="none"}
function loadTodayNote(){note.value=localStorage.getItem("note-"+key)||""}
function saveNote(){updateTodayData();localStorage.setItem("note-"+key,note.value);alert(ui[lang].saved)}
function renderProgress(){let read=0,missed=0;calendar.innerHTML="";for(let i=1;i<=365;i++){const date=new Date(2026,0,i);const k=String(date.getMonth()+1).padStart(2,"0")+"-"+String(date.getDate()).padStart(2,"0");const div=document.createElement("div");div.className="day";div.innerText=i;if(localStorage.getItem("read-"+k)){div.classList.add("read");read++}else if(i<dayOfYear){div.classList.add("missed");missed++}calendar.appendChild(div)}readCount.innerText=read;missedCount.innerText=missed}
function toggleCalendar(){calendar.classList.toggle("hidden")}
function scrollToTop(){window.scrollTo({top:0,behavior:"smooth"})}
function scrollToNotes(){notesTitle.scrollIntoView({behavior:"smooth"})}
window.addEventListener("pageshow",refreshApp);document.addEventListener("visibilitychange",()=>{if(!document.hidden)refreshApp()});setInterval(refreshApp,60000);refreshApp();
